name: PortableChunkLoader
version: 1.0
main: me.okinawaboss.chunkloader.Main
api-version: 1.13
commands:
  cl:
    description: Main command for Chunk Loader plugin
    usage: /cl [give|list|reload]
  chunkloader:
    description: Main command for Chunk Loader plugin
    usage: /cl [give|list|reload]
permissions:
  chunkloader.use:
    description: Allows use of Chunk Loader commands
    default: true
  chunkloader.give:
    description: Allows the player to give chunk loaders
    default: op
  chunkloader.list:
    description: Allows the player to list active chunk loaders
    default: true
  chunkloader.reload:
    description: Allows the player to reload the plugin configuration
    default: op
